# src/state.py
from typing import List, Optional, TypedDict, Annotated
from pydantic import BaseModel, Field
import operator

# --- 1. Domain Models (The Contract) ---

class StockData(BaseModel):
    symbol: str
    current_price: float
    currency: str = "USD"
    # We keep it simple for the assignment

class NewsItem(BaseModel):
    title: str
    summary: str
    source: str

class CompanyResearchDoc(BaseModel):
    """The structured output from the Data Collector Agent"""
    company_name: str
    stock_data: Optional[StockData] = None
    latest_news: List[NewsItem] = Field(default_factory=list)
    source: str = "api" # 'api' or 'mock' to track where data came from

class AnalystReport(BaseModel):
    """The structured output from the Analyst Agent"""
    company_name: str
    summary: str
    key_risks: List[str]
    investment_verdict: str # e.g., "Buy", "Hold", "Sell"

# --- 2. Graph State (The Memory) ---

class AgentState(TypedDict):
    """
    The state of the graph.
    - messages: Holds the conversation history (User <-> Agents)
    - company: The company name user is asking about
    - research_data: The raw data fetched by Collector
    - final_report: The analysis generated by Analyst
    """
    # Uses 'operator.add' to append new messages to history rather than overwriting
    messages: Annotated[List[dict], operator.add] 
    company_name: str
    research_data: Optional[CompanyResearchDoc]
    final_report: Optional[AnalystReport]